### ISSUE TITLE
Unable to Start mnist.py

### ISSUE THREAD

**Issue by wolfysan** [Microsoft/samples-for-ai#76]
Hello,

I tried to run the mnist.py 'Start without Debugging', but I get an error:

`File "samples-for-ai-master\examples\tensorflow\MNIST\mnist.py", line 37, in <module>
    import tensorflow as tf
  File "Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 121, in <module>
    TFE_ContextOptionsSetServerDef = _pywrap_tensorflow_internal.TFE_ContextOptionsSetServerDef
AttributeError: module 'tensorflow.python._pywrap_tensorflow_internal' has no attribute 'TFE_ContextOptionsSetServerDef'`

I think that this is caused by the fact that I am running Python 3.6. Any suggestion on how to fix this issue?

**Comment by amppumas** [comment]
What version of Tensorflow are you using? Did you install it via Microsoft Visual Studio Tools for AI?
`python3 -c 'import tensorflow as tf; print(tf.__version__)'`
It [should ](https://github.com/Microsoft/samples-for-ai#using-a-one-click-installer-to-setup-deep-learning-frameworks) work with python 3.6 and it might be related to [this](https://github.com/tensorflow/tensorflow/issues/16981)

**Comment by wolfysan** [comment]
Hello,

I am using Tensorflow 1.9.0. It got installed when I added the Python Development Environment to visual studio, and Microsoft Visual Studio Tools for AI.

Prior to installing these to Visual studio, I had python 3.6 installed locally, and the package also. Could this be the problem? Do I need to remove all Python related from Visual Studio, and the local ones (Python 3.6 and Anaconda), and reinstall them in Visual Studio only?

**Comment by wolfysan** [comment]
Hello,

Good news. I removed all instances of Python from my PC (Visual studio and standalone), and installed only the Visual Studio related. I managed to make the project work.

In case anyone else has this or a similar problem, they could try the same approach I did.
